# Generated by Django 4.2.7 on 2023-11-22 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(choices=[('RD', 'Red'), ('GR', 'Green'), ('BL', 'Blue'), ('BK', 'Black')], default='BK', max_length=2),
        ),
    ]
